Binomial Distribution

#Question 1a: Investigate the probability distribution of 5 coin tosses and find the probability of getting at least four heads. 

#Steps :  

#1) Investigate the rbinom() function and check all the possible arguments using R's help function. 2) Use rbinom() to generate a simulation of 10,000 tosses and store the outcome to variable x. 3) Create a histogram for x using hist() function 4) Create a new variable y, that stores information about 10 random tosses. 5) Create a histogram for y using hist() function 6) Repeat the steps from 2 to 5. What are the differences you can observe in these histograms? 7) Investigate the dbinom() function to find the probability of getting at least 4 heads. (Hint : you will need to run this command several times and sum. 


set.seed(100)
x <- rbinom(10000,5,0.5) #2
hist(x) #3
y <- rbinom(10,5,0.5) #4
hist(y) #5
dbinom(4,5,0.5) + dbinom(5,5,0.5)  #7

#Question 1b: Find the probability of getting at least four heads out of 5 tosses using the rbinom() function. 

#Steps :  

#1) Use rbinom() to generate a simulation of 10,000 varieties and store the results in variable x. 2) Use the mean() function to estimate at least four heads. 


x <- rbinom(10000,5,0.5)
mean(x >= 4)
dbinom(4,5,.5) + dbinom(5,5,.5)
1-pbinom(3,5,.5) 
#Question 2:  What is the probability of having 2 successes for a random variable X with a distribution of Binomial(6, 1/3).  

#. Binomial(n,p) corresponds to a binomial distribution with n independent Bernoulli trials where probability of success is p. . Investigate the dbinom() function and check all the possible arguments using R's help function. . Investigate the function choose() try to calculate the same probability using the choose function. 


dbinom(2,6,1/3)
choose(6,2)*(1/3)^2*(2/3)^4

#Question 3: Compute the whole sample space for a random variable X with a distribution of Binomial(9, 3/4).  
#. Investigate the dbinom() function and check all the possible arguments using R's help function. 


dbinom(0:9,9,3/4)

#Question 4: For a disease known to have a complication frequency of 20%, a surgeon suggests a new procedure. He tests it on 10 patients and there are no complications. What is the probability of operating on 10 patients successfully with the traditional method?

dbinom(0, size=10, prob=.2)

#Question 5: Suppose there are twelve multiple choice questions in an English class quiz. Each question has five possible answers, and only one of them is correct. Find the probability of having four or less correct answers if a student attempts to answer every question at random. 

#. Investigate the pbinom() function and check all the possible arguments using R help 

# Q5

pbinom(4, size=12, prob=0.2)